site_name: SendCloud 文档中心

site_url: http://sendcloud.sohu.com

repo_url: https://github.com/sendcloud2013/sendcloud_docs/

docs_dir: sources

site_dir: doc

theme_dir: themes/mkdocs

theme_center_lead: false

include_search: true

include_next_prev: false

copyright: Copyright &copy; 2015, SendCloud

author: liubida && lianzimi && xuhong && dianzhang

pages:
# Develop Guide
# - ['guide/index.md', '开发指南', '开发者指南']
# - ['guide/php_rest_guide.md', '开发指南', 'REST API 简易指南（PHP）']
#
- [index.md, '文档首页', '文档首页']
- [guide/base.md, '开发者指南', '基本概念']
- [guide/advance.md, '开发者指南', '高级功能']
- [guide/rule.md, '开发者指南', '通用规则']

#- [email/index.md, '邮件API', '规则']
#- [email/send_email.md, '邮件API', '邮件发送']
#- [email/template_do.md, '邮件API', '邮件模板']
#- [email/list_do.md, '邮件API', '地址列表']
#- [email/label_do.md, '邮件API', '邮件标签']
#- [email/queuestatus_do.md, '邮件API', '队列状态']
#- [email/stats_do.md, '邮件API', '数据统计']
#- [email/user_info.md, '邮件API', '用户信息']
#- [email/bounce_do.md, '邮件API', '退信列表管理']
#- [email/unsubscribe_do.md, '邮件API', '取消订阅管理']
#- [email/spamreported_do.md, '邮件API', '垃圾举报管理']
#- [email/code.md, '邮件API', '代码示例']

- [email_v2/index.md, 'API 2.0', '规则']
- [email_v2/send_email.md, 'API 2.0', '发送相关']
- [email_v2/template_do.md, 'API 2.0', '邮件模板']
- [email_v2/list_do.md, 'API 2.0', '地址列表']
- [email_v2/label_do.md, 'API 2.0', '邮件标签']
- [email_v2/domain_do.md, 'API 2.0', '域名']
- [email_v2/apiuser_do.md, 'API 2.0', 'API_USER']
- [email_v2/user_info.md, 'API 2.0', '用户信息']
#- [email_v2/queuestatus_do.md, '邮件API v2', '队列状态']
- [email_v2/stats_do.md, 'API 2.0', '数据统计']
- [email_v2/deliver_response.md, 'API 2.0', '投递回应']
- [email_v2/bounce_do.md, 'API 2.0', '退信列表管理']
- [email_v2/unsubscribe_do.md, 'API 2.0', '取消订阅管理']
- [email_v2/spamreported_do.md, 'API 2.0', '垃圾举报管理']
#- [email_v2/webhook.md, '邮件API v2', 'WebHook 详细']
- [email_v2/code.md, 'API 2.0', '代码示例']

- [sms/index.md, '短信API', '规则']
- [sms/api.md, '短信API', '发送相关']
- [sms/code.md, '短信API', '短信代码示例']
- [sms/code_voice.md, '短信API', '语音代码示例']
- [sms/sms_template.md, '短信API', '短信模板']
- [sms/code_sms_template.md, '短信API', '短信模板代码示例']
- [sms/sms_data.md, '短信API', '数据统计']
- [sms/code_data.md, '短信API', '数据统计代码示例']

- [sdk/java.md, 'SDK文档', 'Java']

#- [downloads/index.md, '代码示例', '代码示例']
#- [downloads/code/curl.md, '代码示例','Curl']
#- [downloads/code/python/python.md, '代码示例','Python']
#- [downloads/code/java/java.md, '代码示例','Java']
#- [downloads/code/php/php.md, '代码示例','PHP']
#- [downloads/code/ruby/ruby.md, '代码示例','Ruby']
#- [downloads/code/perl/perl.md, '代码示例','Perl']
#- [downloads/code/csharp.md, '代码示例','C#']
#- [downloads/code/golang.md, '代码示例','Golang']
#- [downloads/code/nodejs.md, '代码示例','Nodejs']

- [faq/index.md, 'FAQ', 'FAQ']
- [test/index.md, 'TRY IT', 'TRY IT']

# theme: mkdocs
